### ISSUE TITLE
Update the driver app to take width and height arguments

### ISSUE THREAD

**Issue by wliao008** [wliao008/gaze#6]
With
```
$ ./gmaze
```
output a default sized maze, but update it to
```
$ ./gmaze -w 10 -h 20
```
to do a customized size.

**Comment by desdulianto** [comment]
Can I contribute?

Is the flag mandatory, both of them or you can specify only -w or -h or if nothing specified it will generate maze with default width and height.

thanks.

**Comment by wliao008** [comment]
Hi, yep feel free to submit pull request.

The flags don't have to be mandatory, they could have default values (currently [hard coded](https://github.com/wliao008/gaze/blob/master/cmd/gaze/main.go#L10))

Some example usages could be
```
$ go run main.go //generate the maze with the default size
```

```
$ go run main.go -w 20 //generate the maze with the width 20, and default height
```

```
$ go run main.go -h 8 //generate the maze with the height 8, and default width
```
or
```
$ go run main.go -w 20 -h 8
```
